### ISSUE TITLE
Check ruby styleguide, fix the code.

### ISSUE THREAD

**Issue by vfreefly** [imogikan/first_repository#1]
Read it https://github.com/arbox/ruby-style-guide/blob/master/README-ruRU.md

And fix your code https://github.com/imogikan/first_repository/blob/master/main.rb

And don't do that's fucked up with code indentation ever again. Please

**Comment by vfreefly** [comment]
Updated a correct link to the ruby style guide manual https://github.com/arbox/ruby-style-guide/blob/master/README-ruRU.md

**Comment by imogikan** [comment]
Done
updated file https://github.com/imogikan/first_repository/blob/master/main.rb
@vfreefly

**Comment by vfreefly** [comment]
all is fine, closed
