### ISSUE TITLE
Fix the structure of paths 

### ISSUE THREAD

**Issue by vfreefly** [imogikan/first_repository#4]
See screenshot http://joxi.ru/DmBBqnGcNELVYm

**Comment by vfreefly** [comment]
@imogikan  
not exactly http://joxi.ru/v29Bo41cG1oNdA 
I see nothing on the root path of the website

**Comment by imogikan** [comment]
@vfreefly  I made a stupid mistake. Now the bug is fixed

**Comment by vfreefly** [comment]
@imogikan 
Alright, this part is done.
