### ISSUE TITLE
Make the app dynamic by storing info about chaynaya's in the simple csv database

### ISSUE THREAD

**Issue by vfreefly** [imogikan/first_repository#8]
So, you should store all info about 3 chainaya's in the csv file.  

When there is request to /catalog , your app should read the csv file, convert it to ruby hash (for simplicity), and pass this hash with chaynayas to the calalog view, where you should render all chaynaya's as an html code. For it use sinatra's instance variables and to render code in the view use `<%= %>` .

When there is request to the /catalog/some_chainaya, you should check, if there in csv, chainaya with this path, if so, pass to the chainaya template an instance variable, and render an html with this info.

It's a big step, take your time.

**Comment by imogikan** [comment]
well, it was a difficult task for me. Please, check it.

**Comment by vfreefly** [comment]
@imogikan 
Any reason why you readed csv here https://github.com/imogikan/first_repository/blob/master/views/layout.erb but don't use it at all?

**Comment by vfreefly** [comment]
@imogikan Modify your csv like this:
```
id | name           | short_description          | long_description   | address 
1  | City of London | Уютное местечко, недорого. | Типичный блядушник | Карла Маркса 177в
```
Fill in other 2 the same way.

**Comment by vfreefly** [comment]
3. Move teaplace.csv into subfolder `/database`
@imogikan

**Comment by imogikan** [comment]
all done. @vfreefly

**Comment by vfreefly** [comment]
closed
