### ISSUE TITLE
Store all database logic only in routes. Refactor catalog

### ISSUE THREAD

**Issue by vfreefly** [imogikan/first_repository#9]
This file is main https://github.com/imogikan/first_repository/blob/master/main.rb 
It should have all logic for csv database and so on.

You should NOT do any operations with a database inside views. Like here https://github.com/imogikan/first_repository/blob/master/views/catalog.erb

1. Delete all database code from https://github.com/imogikan/first_repository/blob/master/views/catalog.erb

In the main.rb
2. Put this code into method, `def database` 
```
extracted_data = CSV.table('teaplace.csv', header_converters: nil)
transformed_data = extracted_data.each { |row| p row.to_hash }
@first = transformed_data[0]['name']
@second = transformed_data[1]['name']
@third = transformed_data[2]['name']
```
`transformed_data = extracted_data.each { |row| p row.to_hash }` delete this
Delete this as well 
```
@first = transformed_data[0]['name']
@second = transformed_data[1]['name']
@third = transformed_data[2]['name']
```
3. In the route 
```
  get do
    erb :catalog
  end
```

Define instance variable @chainayas with all chainayas from the db. `@chainayas = database`
If you read sinatra manual very well, you should know what all instance variable defined in the route, will be available in the regarded view, it our case in the `erb :catalog` :catalog view.

4. So, this code in catalog:
```
<div class="features">
  <ul>
    <li class="feature-item">
      <h2><a href="/catalog/city_of_london">1.<%= @first %></a></h2>
      <p>Уютное местечко, недорого.</p>
    </li>
    <li class="feature-item">
      <h2><a href="/catalog/city_of_london_bar">2.<%= @second %></a></h2>
      <p>Уютное местечко, недорого,но около всегда быдло </p>
    </li>
    <li class="feature-item">
      <h2><a href="/catalog/mojo">3.<%= @third %></a></h2>
      <p>Неуютное местечко, прям по нищебродски все, особенно кальяны</p>
    </li>
  </ul>
</div>
```
You should instead, iterate all items in @chainayas (It's automatically available already in :catalog view, remember). To do it, read here example https://learn.co/lessons/sinatra-view-and-controller-readme-walkthrough , scroll to "Iterating in ERB".

And yes, forget about chainayas routes for now, you should fix only the catalog view.

**Comment by imogikan** [comment]
added logic to this app. But an error occurred. I can't add a link for any chaynaya @vfreefly

**Comment by imogikan** [comment]
`extracted_data = CSV.table('database/teaplace.csv', header_converters: nil)
transformed_data = extracted_data.each do |row|
  @row = row.to_hash
  p @row['name']
end`

**Comment by vfreefly** [comment]
@imogikan  
In the next time, when you saying what you've done something, please provide a link to this commit. All commits you can find here https://github.com/imogikan/first_repository/commits/master

**Comment by imogikan** [comment]
Ok, i'am understended you

**Comment by vfreefly** [comment]
@imogikan  https://github.com/imogikan/first_repository/issues/9#issuecomment-385614132

Forget about chainaya pages for now. They should't work for now, that's ok.

Here https://github.com/imogikan/first_repository/blob/2ed445251a5b7e788c169c891dbdf3b2c6288525/views/catalog.erb
1. Fix indentation
2. Here `transformed_data = @extracted_data.each` why do you need this part? `transformed_data = ` get rid of it

Here https://github.com/imogikan/first_repository/blob/2ed445251a5b7e788c169c891dbdf3b2c6288525/main.rb
1. Here ` @extracted_data = CSV.table('database/teaplace.csv', header_converters: nil)`. You should think first how to call your variables. "extracted_data" ? What's the data? Rename it to `@chaynayas`. Or find a correct english word for chainayas all call it using this correct name.

After renaming we are going again to https://github.com/imogikan/first_repository/blob/2ed445251a5b7e788c169c891dbdf3b2c6288525/views/catalog.erb
```
@extracted_data.each do |row|
``` 
You can change to 
```
@chainayas.each do |chaynaya|

```

and then `<%= chainaya['link_into'] %>` and so on.

Much more understandable, isn't it? @imogikan

**Comment by imogikan** [comment]
All done. [](https://github.com/imogikan/first_repository/commit/398e994124c93e979cabda29a724d2deec50577e) - is this link? @vfreefly

**Comment by vfreefly** [comment]
Yes, commit link is correct.

YOUR indentation should be like this:
```ruby
```

**Comment by imogikan** [comment]
Now i didn't understand you. What does it mean?

**Comment by vfreefly** [comment]
Link is correct.

Now, https://github.com/imogikan/first_repository/blob/master/main.rb
```
 @info_about_tea_place = CSV.table('database/teaplace.csv', header_converters: nil)
```

I said you what you should convert csv into array of hashes. 
But I see, what this object is not hash, it's a csv object. http://joxi.ru/5mdL50ECvbN4Rm

`@info_about_tea_place` should be ARRAY of HASHES. Each hash should be key value info about chainaya. Find your converter or google again how to convert csv into array of hashes using ruby.

@imogikan

**Comment by vfreefly** [comment]
@imogikan  https://github.com/imogikan/first_repository/issues/9#issuecomment-385628144
I edited comment, see above

**Comment by imogikan** [comment]
Check it. https://github.com/imogikan/first_repository/commit/156c15802358a92319f7ef783282d8de25a24912
I'm not sure that's all right. @vfreefly

**Comment by vfreefly** [comment]
1. This is correct https://github.com/imogikan/first_repository/blob/156c15802358a92319f7ef783282d8de25a24912/main.rb
You are finally got array of hashes.

2. 
Here https://github.com/imogikan/first_repository/blob/156c15802358a92319f7ef783282d8de25a24912/views/catalog.erb#L2 okay, do you feel the difference between `each` and `map` for array objects? Any reason why do you need each there?

Here https://github.com/imogikan/first_repository/blob/156c15802358a92319f7ef783282d8de25a24912/views/catalog.erb#L3 so why do you need still convert a hash to the hash? It's already hash. Got it? Delete this part.

And, remember, map and each is a totally different methods. 
@imogikan

**Comment by imogikan** [comment]
Fixed. @vfreefly  https://github.com/imogikan/first_repository/commit/929b693f9301642fcd6a1a56c4a5a88a6b1dc412

**Comment by vfreefly** [comment]
@imogikan 
Nice, but didn't see what you fixed map to each in the catalog view

**Comment by imogikan** [comment]
The last version code, here 
https://github.com/imogikan/first_repository/commit/2214880451083610ae13444e4fa8f0307834ccf7
@vfreefly

**Comment by vfreefly** [comment]
@imogikan 
Good.
Btw, why there is space between object and method `@info_about_tea_place. each`

**Comment by imogikan** [comment]
I already corrected this error. In the next version of the code you will see. @vfreefly

**Comment by vfreefly** [comment]
@imogikan 

Now it's time to fix chainayas pages.

Get rid of it https://github.com/imogikan/first_repository/blob/master/main.rb#L24-L34 . You don't need it.

Also delete 2 views here https://github.com/imogikan/first_repository/tree/master/views/teaplace and leave only one. You'll be use it as an template for any chainaya page. Rename this file to `tea_place.erb`. Also, get rid from `/views/teaplace` folder and move `tea_place.erb` to the `/views` folder. 

1. Fix your csv: delete column `link_into` and instead add column `id`. You have 3 chaynayas. Each chainaya should have an ID. First - 1, Second - 2, Third - 3.

2. Read about params in Sinatra. Google about it. 

3. Create route
```
namespace '/catalog' do
  get '/:id' do
    erb :tea_place
  end
end
```
Using params[:id] find in the csv a regarded chainaya hash and pass it to `@chainaya` variable.

4. In the view tea_place render all info about this chainaya by using `@chainaya` variable.

**Comment by imogikan** [comment]
last working version, here's 
35e3125c68d0a404a432eecc20e8bc5ed5ba1cfd
@vfreefly

**Comment by imogikan** [comment]
Finally, done @vfreefly   e0dfc2823f4ec631e090d590a32924f6e3d7294e

**Comment by vfreefly** [comment]
@imogikan 

https://github.com/imogikan/first_repository/blob/master/main.rb
1. Fix indentation
2. binding.pry? It SHOULD not be in your code at the github! It's only for debugging. Don't forget always delete it when you finished your debugging. 
3. Do you know the difference between instance variables and normal variables? Any reason why here, in the method, you are using instance variable? https://github.com/imogikan/first_repository/blob/master/main.rb#L12

4. You repeated `@chainaya` 3 times. https://github.com/imogikan/first_repository/blob/master/main.rb#L30-L32 What for?

**Comment by imogikan** [comment]
All done bbf2805fa95fa74e196113f013a6eda46071aeeb
@vfreefly

**Comment by vfreefly** [comment]
@imogikan 

perfect. All done
